### ISSUE TITLE
#renderer.renderLists.get is called with 'camera' when it expects renderCallDepth

### ISSUE THREAD

**Issue by ittayd** [bzztbomb/three_js_gpu_picking#4]
Using the latest three.js library

**Comment by acthp** [comment]
Any workarounds for this?

**Comment by bzztbomb** [comment]
There's a PR for this, I haven't had a moment to merge it, but in the meantime, check it out!

https://github.com/bzztbomb/three_js_gpu_picking/pull/3

**Comment by bzztbomb** [comment]
Finally got around to updating and publishing with the fix.  1.0.1 works with r131.

Thanks!
