### ISSUE TITLE
Using MeshPhysicalMaterial doesn't work even if setting a pickingMaterial

### ISSUE THREAD

**Issue by ittayd** [bzztbomb/three_js_gpu_picking#5]
I set my meshe's material to `new THREE.MeshPhysicalMaterial({metalness:0, roughness: 0.7, reflectivity: 0.5, transmission: 0.5})`
I set pickingMaterial to `new THREE.MeshBasicMaterial( { vertexColors: true }`

But it seems that iterating on objects to get the picking material is through renderList.opaque which returns an empty list (in newest three.js)

**Comment by bzztbomb** [comment]
Fixed in 1.0.2.

Thanks for the pointer on where to look, there's another list `transmissive` that contains any geometry with a `MeshPhysicalMaterial` that has a `transmission` property greater than 0.
