### ISSUE TITLE
Doesn't work on Chrome on Android

### ISSUE THREAD

**Issue by ittayd** [bzztbomb/three_js_gpu_picking#6]
Items get processed, but the pixelBuffer returns 255s. I don't understand the mechanism well enough to debug further. My code doesn't have any special handling for mobile.

**Comment by ittayd** [comment]
It seems the instructions in the readme are wrong. They have `  var objectId = picker.pick(ev.clientX / window.devicePixelRatio, ev.clientY / window.devicePixelRatio, obj => {` where actually clientX and clientY should be multiplied by the pixel ratio

**Comment by bzztbomb** [comment]
Apologies for crap docs!  It was an artifact of the example handling pixel ratios a little oddly. Updated!
