### ISSUE TITLE
not working properly for sprite when it's  center is not the default value (0.5, 0.5).

### ISSUE THREAD

**Issue by DevinCarl** [bzztbomb/three_js_gpu_picking#8]
I found that when the center of  sprite is not the default value (0.5, 0.5), gpu_picking is not working properly.
is there any way to solve it?

```
const sprite = new Sprite(new SpriteMaterial({
  color: 'blue',
}));

sprite.center.set(0.5, 0);

scene.add(sprite);
```

**Comment by bzztbomb** [comment]
I don't have time to test right now, but it looks like we need to use `sprite_vert` [here](https://github.com/bzztbomb/three_js_gpu_picking/blob/main/src/gpupicker.js#L104) when it is a `SpriteMaterial`. You'll need to add    the spritematerial case to the index as well.

I can play around with it this weekend, but if you need it faster, that's the general fix.

**Comment by bzztbomb** [comment]
Thanks to @bennlich for a [fix](https://github.com/bzztbomb/three_js_gpu_picking/pull/9) to this issue.  It's rad to have someone else helping out with this project! Thank you again!
